asm("handle_interrupts_trampoline:");
asm("jmp handle_interrupts");
asm("");
asm(".local   handle_interrupts");
asm("isr_asm:");
asm("// manual push registers:");
asm("sub $0xa0, %rsp   // make room for the manual-pushed registers.");
asm("movq    %r15, 0x90(%rsp)//");
asm("movq    %r14, 0x88(%rsp)//");
asm("movq    %r13, 0x80(%rsp)//");
asm("movq    %r12, 0x78(%rsp)//");
asm("movq    %r11, 0x70(%rsp)//");
asm("movq    %r10, 0x68(%rsp)//");
asm("movq    %r9,  0x60(%rsp)//");
asm("movq    %r8,  0x58(%rsp)//");
asm("movq    %rsi, 0x50(%rsp)//");
asm("movq    %rdi, 0x48(%rsp)//");
asm("movq    %rbp, 0x40(%rsp)//");
asm("movq    %rdx, 0x38(%rsp)//");
asm("movq    %rcx, 0x30(%rsp)//");
asm("movq    %rbx, 0x28(%rsp)//");
asm("movq    %rax, 0x20(%rsp)//");
asm("xorl    %eax, %eax//");
asm("movw    %gs, %ax//");
asm("movq    %rax, 0x18(%rsp)//");
asm("movw    %fs, %ax//");
asm("movq    %rax, 0x10(%rsp)//");
asm("movw    %es, %ax//");
asm("movq    %rax, 0x08(%rsp)//");
asm("movw    %ds, %ax//");
asm("movq    %rax, 0x00(%rsp)//");
asm("");
asm("// Call the C handle routine");
asm("//push %rsp // move the Registers struct as parameter.");
asm("movq    %rsp, %rdi // move the Registers struct as parameter.");
asm("//add $8, %rdi");
asm("cld // /* C code following the sysV ABI requires DF to be clear on function entry */");
asm("call handle_interrupts_trampoline // C routine");
asm("//add $8, %rsp//");
asm("");
asm("// Manual pop the registers:");
asm("movq    0x00(%rsp), %rax//");
asm("movw    %ax, %ds//");
asm("movq    0x08(%rsp), %rax//");
asm("movw    %ax, %es//");
asm("movq    0x10(%rsp), %rax//");
asm("movw    %ax, %fs//");
asm("movq    0x18(%rsp), %rax//");
asm("movw    %ax, %gs//");
asm("");
asm("movq    0x20(%rsp), %rax //");
asm("movq    0x28(%rsp), %rbx //");
asm("movq    0x30(%rsp), %rcx //");
asm("movq    0x38(%rsp), %rdx //");
asm("movq    0x40(%rsp), %rbp //");
asm("movq    0x48(%rsp), %rdi //");
asm("movq    0x50(%rsp), %rsi //");
asm("movq    0x58(%rsp),  %r8  //");
asm("movq    0x60(%rsp),  %r9  //");
asm("movq    0x68(%rsp), %r10 //");
asm("movq    0x70(%rsp), %r11 //");
asm("movq    0x78(%rsp), %r12 //");
asm("movq    0x80(%rsp), %r13 //");
asm("movq    0x88(%rsp), %r14 //");
asm("movq    0x90(%rsp), %r15 //");
asm("add $0xa0, %rsp   // restore %rsp");
asm("ret //");
asm("");
asm(".local   isr_wrapper0");
asm(".align   4");
asm("");
asm("isr_wrapper0:");
asm("push $0 // push dummy error code");
asm("push $0 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper1");
asm(".align   4");
asm("");
asm("isr_wrapper1:");
asm("push $0 // push dummy error code");
asm("push $1 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper2");
asm(".align   4");
asm("");
asm("isr_wrapper2:");
asm("push $0 // push dummy error code");
asm("push $2 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper3");
asm(".align   4");
asm("");
asm("isr_wrapper3:");
asm("push $0 // push dummy error code");
asm("push $3 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper4");
asm(".align   4");
asm("");
asm("isr_wrapper4:");
asm("push $0 // push dummy error code");
asm("push $4 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper5");
asm(".align   4");
asm("");
asm("isr_wrapper5:");
asm("push $0 // push dummy error code");
asm("push $5 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper6");
asm(".align   4");
asm("");
asm("isr_wrapper6:");
asm("push $0 // push dummy error code");
asm("push $6 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper7");
asm(".align   4");
asm("");
asm("isr_wrapper7:");
asm("push $0 // push dummy error code");
asm("push $7 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper8");
asm(".align   4");
asm("");
asm("isr_wrapper8:");
asm("");
asm("push $8 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper9");
asm(".align   4");
asm("");
asm("isr_wrapper9:");
asm("push $0 // push dummy error code");
asm("push $9 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper10");
asm(".align   4");
asm("");
asm("isr_wrapper10:");
asm("");
asm("push $10 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper11");
asm(".align   4");
asm("");
asm("isr_wrapper11:");
asm("");
asm("push $11 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper12");
asm(".align   4");
asm("");
asm("isr_wrapper12:");
asm("");
asm("push $12 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper13");
asm(".align   4");
asm("");
asm("isr_wrapper13:");
asm("");
asm("push $13 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper14");
asm(".align   4");
asm("");
asm("isr_wrapper14:");
asm("");
asm("push $14 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper15");
asm(".align   4");
asm("");
asm("isr_wrapper15:");
asm("push $0 // push dummy error code");
asm("push $15 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper16");
asm(".align   4");
asm("");
asm("isr_wrapper16:");
asm("push $0 // push dummy error code");
asm("push $16 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper17");
asm(".align   4");
asm("");
asm("isr_wrapper17:");
asm("");
asm("push $17 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper18");
asm(".align   4");
asm("");
asm("isr_wrapper18:");
asm("push $0 // push dummy error code");
asm("push $18 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper19");
asm(".align   4");
asm("");
asm("isr_wrapper19:");
asm("push $0 // push dummy error code");
asm("push $19 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper20");
asm(".align   4");
asm("");
asm("isr_wrapper20:");
asm("push $0 // push dummy error code");
asm("push $20 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper21");
asm(".align   4");
asm("");
asm("isr_wrapper21:");
asm("push $0 // push dummy error code");
asm("push $21 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper22");
asm(".align   4");
asm("");
asm("isr_wrapper22:");
asm("push $0 // push dummy error code");
asm("push $22 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper23");
asm(".align   4");
asm("");
asm("isr_wrapper23:");
asm("push $0 // push dummy error code");
asm("push $23 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper24");
asm(".align   4");
asm("");
asm("isr_wrapper24:");
asm("push $0 // push dummy error code");
asm("push $24 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper25");
asm(".align   4");
asm("");
asm("isr_wrapper25:");
asm("push $0 // push dummy error code");
asm("push $25 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper26");
asm(".align   4");
asm("");
asm("isr_wrapper26:");
asm("push $0 // push dummy error code");
asm("push $26 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper27");
asm(".align   4");
asm("");
asm("isr_wrapper27:");
asm("push $0 // push dummy error code");
asm("push $27 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper28");
asm(".align   4");
asm("");
asm("isr_wrapper28:");
asm("push $0 // push dummy error code");
asm("push $28 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper29");
asm(".align   4");
asm("");
asm("isr_wrapper29:");
asm("push $0 // push dummy error code");
asm("push $29 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper30");
asm(".align   4");
asm("");
asm("isr_wrapper30:");
asm("push $0 // push dummy error code");
asm("push $30 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper31");
asm(".align   4");
asm("");
asm("isr_wrapper31:");
asm("push $0 // push dummy error code");
asm("push $31 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper32");
asm(".align   4");
asm("");
asm("isr_wrapper32:");
asm("push $0 // push dummy error code");
asm("push $32 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper33");
asm(".align   4");
asm("");
asm("isr_wrapper33:");
asm("push $0 // push dummy error code");
asm("push $33 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper34");
asm(".align   4");
asm("");
asm("isr_wrapper34:");
asm("push $0 // push dummy error code");
asm("push $34 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper35");
asm(".align   4");
asm("");
asm("isr_wrapper35:");
asm("push $0 // push dummy error code");
asm("push $35 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper36");
asm(".align   4");
asm("");
asm("isr_wrapper36:");
asm("push $0 // push dummy error code");
asm("push $36 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper37");
asm(".align   4");
asm("");
asm("isr_wrapper37:");
asm("push $0 // push dummy error code");
asm("push $37 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper38");
asm(".align   4");
asm("");
asm("isr_wrapper38:");
asm("push $0 // push dummy error code");
asm("push $38 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper39");
asm(".align   4");
asm("");
asm("isr_wrapper39:");
asm("push $0 // push dummy error code");
asm("push $39 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper40");
asm(".align   4");
asm("");
asm("isr_wrapper40:");
asm("push $0 // push dummy error code");
asm("push $40 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper41");
asm(".align   4");
asm("");
asm("isr_wrapper41:");
asm("push $0 // push dummy error code");
asm("push $41 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper42");
asm(".align   4");
asm("");
asm("isr_wrapper42:");
asm("push $0 // push dummy error code");
asm("push $42 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper43");
asm(".align   4");
asm("");
asm("isr_wrapper43:");
asm("push $0 // push dummy error code");
asm("push $43 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper44");
asm(".align   4");
asm("");
asm("isr_wrapper44:");
asm("push $0 // push dummy error code");
asm("push $44 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper45");
asm(".align   4");
asm("");
asm("isr_wrapper45:");
asm("push $0 // push dummy error code");
asm("push $45 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper46");
asm(".align   4");
asm("");
asm("isr_wrapper46:");
asm("push $0 // push dummy error code");
asm("push $46 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper47");
asm(".align   4");
asm("");
asm("isr_wrapper47:");
asm("push $0 // push dummy error code");
asm("push $47 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper48");
asm(".align   4");
asm("");
asm("isr_wrapper48:");
asm("push $0 // push dummy error code");
asm("push $48 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper49");
asm(".align   4");
asm("");
asm("isr_wrapper49:");
asm("push $0 // push dummy error code");
asm("push $49 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper50");
asm(".align   4");
asm("");
asm("isr_wrapper50:");
asm("push $0 // push dummy error code");
asm("push $50 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper51");
asm(".align   4");
asm("");
asm("isr_wrapper51:");
asm("push $0 // push dummy error code");
asm("push $51 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper52");
asm(".align   4");
asm("");
asm("isr_wrapper52:");
asm("push $0 // push dummy error code");
asm("push $52 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper53");
asm(".align   4");
asm("");
asm("isr_wrapper53:");
asm("push $0 // push dummy error code");
asm("push $53 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper54");
asm(".align   4");
asm("");
asm("isr_wrapper54:");
asm("push $0 // push dummy error code");
asm("push $54 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper55");
asm(".align   4");
asm("");
asm("isr_wrapper55:");
asm("push $0 // push dummy error code");
asm("push $55 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper56");
asm(".align   4");
asm("");
asm("isr_wrapper56:");
asm("push $0 // push dummy error code");
asm("push $56 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper57");
asm(".align   4");
asm("");
asm("isr_wrapper57:");
asm("push $0 // push dummy error code");
asm("push $57 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper58");
asm(".align   4");
asm("");
asm("isr_wrapper58:");
asm("push $0 // push dummy error code");
asm("push $58 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper59");
asm(".align   4");
asm("");
asm("isr_wrapper59:");
asm("push $0 // push dummy error code");
asm("push $59 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper60");
asm(".align   4");
asm("");
asm("isr_wrapper60:");
asm("push $0 // push dummy error code");
asm("push $60 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper61");
asm(".align   4");
asm("");
asm("isr_wrapper61:");
asm("push $0 // push dummy error code");
asm("push $61 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper62");
asm(".align   4");
asm("");
asm("isr_wrapper62:");
asm("push $0 // push dummy error code");
asm("push $62 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper63");
asm(".align   4");
asm("");
asm("isr_wrapper63:");
asm("push $0 // push dummy error code");
asm("push $63 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper64");
asm(".align   4");
asm("");
asm("isr_wrapper64:");
asm("push $0 // push dummy error code");
asm("push $64 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper65");
asm(".align   4");
asm("");
asm("isr_wrapper65:");
asm("push $0 // push dummy error code");
asm("push $65 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper66");
asm(".align   4");
asm("");
asm("isr_wrapper66:");
asm("push $0 // push dummy error code");
asm("push $66 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper67");
asm(".align   4");
asm("");
asm("isr_wrapper67:");
asm("push $0 // push dummy error code");
asm("push $67 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper68");
asm(".align   4");
asm("");
asm("isr_wrapper68:");
asm("push $0 // push dummy error code");
asm("push $68 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper69");
asm(".align   4");
asm("");
asm("isr_wrapper69:");
asm("push $0 // push dummy error code");
asm("push $69 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper70");
asm(".align   4");
asm("");
asm("isr_wrapper70:");
asm("push $0 // push dummy error code");
asm("push $70 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper71");
asm(".align   4");
asm("");
asm("isr_wrapper71:");
asm("push $0 // push dummy error code");
asm("push $71 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper72");
asm(".align   4");
asm("");
asm("isr_wrapper72:");
asm("push $0 // push dummy error code");
asm("push $72 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper73");
asm(".align   4");
asm("");
asm("isr_wrapper73:");
asm("push $0 // push dummy error code");
asm("push $73 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper74");
asm(".align   4");
asm("");
asm("isr_wrapper74:");
asm("push $0 // push dummy error code");
asm("push $74 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper75");
asm(".align   4");
asm("");
asm("isr_wrapper75:");
asm("push $0 // push dummy error code");
asm("push $75 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper76");
asm(".align   4");
asm("");
asm("isr_wrapper76:");
asm("push $0 // push dummy error code");
asm("push $76 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper77");
asm(".align   4");
asm("");
asm("isr_wrapper77:");
asm("push $0 // push dummy error code");
asm("push $77 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper78");
asm(".align   4");
asm("");
asm("isr_wrapper78:");
asm("push $0 // push dummy error code");
asm("push $78 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper79");
asm(".align   4");
asm("");
asm("isr_wrapper79:");
asm("push $0 // push dummy error code");
asm("push $79 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper80");
asm(".align   4");
asm("");
asm("isr_wrapper80:");
asm("push $0 // push dummy error code");
asm("push $80 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper81");
asm(".align   4");
asm("");
asm("isr_wrapper81:");
asm("push $0 // push dummy error code");
asm("push $81 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper82");
asm(".align   4");
asm("");
asm("isr_wrapper82:");
asm("push $0 // push dummy error code");
asm("push $82 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper83");
asm(".align   4");
asm("");
asm("isr_wrapper83:");
asm("push $0 // push dummy error code");
asm("push $83 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper84");
asm(".align   4");
asm("");
asm("isr_wrapper84:");
asm("push $0 // push dummy error code");
asm("push $84 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper85");
asm(".align   4");
asm("");
asm("isr_wrapper85:");
asm("push $0 // push dummy error code");
asm("push $85 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper86");
asm(".align   4");
asm("");
asm("isr_wrapper86:");
asm("push $0 // push dummy error code");
asm("push $86 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper87");
asm(".align   4");
asm("");
asm("isr_wrapper87:");
asm("push $0 // push dummy error code");
asm("push $87 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper88");
asm(".align   4");
asm("");
asm("isr_wrapper88:");
asm("push $0 // push dummy error code");
asm("push $88 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper89");
asm(".align   4");
asm("");
asm("isr_wrapper89:");
asm("push $0 // push dummy error code");
asm("push $89 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper90");
asm(".align   4");
asm("");
asm("isr_wrapper90:");
asm("push $0 // push dummy error code");
asm("push $90 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper91");
asm(".align   4");
asm("");
asm("isr_wrapper91:");
asm("push $0 // push dummy error code");
asm("push $91 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper92");
asm(".align   4");
asm("");
asm("isr_wrapper92:");
asm("push $0 // push dummy error code");
asm("push $92 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper93");
asm(".align   4");
asm("");
asm("isr_wrapper93:");
asm("push $0 // push dummy error code");
asm("push $93 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper94");
asm(".align   4");
asm("");
asm("isr_wrapper94:");
asm("push $0 // push dummy error code");
asm("push $94 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper95");
asm(".align   4");
asm("");
asm("isr_wrapper95:");
asm("push $0 // push dummy error code");
asm("push $95 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper96");
asm(".align   4");
asm("");
asm("isr_wrapper96:");
asm("push $0 // push dummy error code");
asm("push $96 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper97");
asm(".align   4");
asm("");
asm("isr_wrapper97:");
asm("push $0 // push dummy error code");
asm("push $97 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper98");
asm(".align   4");
asm("");
asm("isr_wrapper98:");
asm("push $0 // push dummy error code");
asm("push $98 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper99");
asm(".align   4");
asm("");
asm("isr_wrapper99:");
asm("push $0 // push dummy error code");
asm("push $99 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper100");
asm(".align   4");
asm("");
asm("isr_wrapper100:");
asm("push $0 // push dummy error code");
asm("push $100 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper101");
asm(".align   4");
asm("");
asm("isr_wrapper101:");
asm("push $0 // push dummy error code");
asm("push $101 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper102");
asm(".align   4");
asm("");
asm("isr_wrapper102:");
asm("push $0 // push dummy error code");
asm("push $102 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper103");
asm(".align   4");
asm("");
asm("isr_wrapper103:");
asm("push $0 // push dummy error code");
asm("push $103 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper104");
asm(".align   4");
asm("");
asm("isr_wrapper104:");
asm("push $0 // push dummy error code");
asm("push $104 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper105");
asm(".align   4");
asm("");
asm("isr_wrapper105:");
asm("push $0 // push dummy error code");
asm("push $105 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper106");
asm(".align   4");
asm("");
asm("isr_wrapper106:");
asm("push $0 // push dummy error code");
asm("push $106 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper107");
asm(".align   4");
asm("");
asm("isr_wrapper107:");
asm("push $0 // push dummy error code");
asm("push $107 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper108");
asm(".align   4");
asm("");
asm("isr_wrapper108:");
asm("push $0 // push dummy error code");
asm("push $108 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper109");
asm(".align   4");
asm("");
asm("isr_wrapper109:");
asm("push $0 // push dummy error code");
asm("push $109 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper110");
asm(".align   4");
asm("");
asm("isr_wrapper110:");
asm("push $0 // push dummy error code");
asm("push $110 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper111");
asm(".align   4");
asm("");
asm("isr_wrapper111:");
asm("push $0 // push dummy error code");
asm("push $111 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper112");
asm(".align   4");
asm("");
asm("isr_wrapper112:");
asm("push $0 // push dummy error code");
asm("push $112 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper113");
asm(".align   4");
asm("");
asm("isr_wrapper113:");
asm("push $0 // push dummy error code");
asm("push $113 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper114");
asm(".align   4");
asm("");
asm("isr_wrapper114:");
asm("push $0 // push dummy error code");
asm("push $114 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper115");
asm(".align   4");
asm("");
asm("isr_wrapper115:");
asm("push $0 // push dummy error code");
asm("push $115 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper116");
asm(".align   4");
asm("");
asm("isr_wrapper116:");
asm("push $0 // push dummy error code");
asm("push $116 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper117");
asm(".align   4");
asm("");
asm("isr_wrapper117:");
asm("push $0 // push dummy error code");
asm("push $117 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper118");
asm(".align   4");
asm("");
asm("isr_wrapper118:");
asm("push $0 // push dummy error code");
asm("push $118 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper119");
asm(".align   4");
asm("");
asm("isr_wrapper119:");
asm("push $0 // push dummy error code");
asm("push $119 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper120");
asm(".align   4");
asm("");
asm("isr_wrapper120:");
asm("push $0 // push dummy error code");
asm("push $120 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper121");
asm(".align   4");
asm("");
asm("isr_wrapper121:");
asm("push $0 // push dummy error code");
asm("push $121 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper122");
asm(".align   4");
asm("");
asm("isr_wrapper122:");
asm("push $0 // push dummy error code");
asm("push $122 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper123");
asm(".align   4");
asm("");
asm("isr_wrapper123:");
asm("push $0 // push dummy error code");
asm("push $123 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper124");
asm(".align   4");
asm("");
asm("isr_wrapper124:");
asm("push $0 // push dummy error code");
asm("push $124 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper125");
asm(".align   4");
asm("");
asm("isr_wrapper125:");
asm("push $0 // push dummy error code");
asm("push $125 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper126");
asm(".align   4");
asm("");
asm("isr_wrapper126:");
asm("push $0 // push dummy error code");
asm("push $126 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper127");
asm(".align   4");
asm("");
asm("isr_wrapper127:");
asm("push $0 // push dummy error code");
asm("push $127 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper128");
asm(".align   4");
asm("");
asm("isr_wrapper128:");
asm("push $0 // push dummy error code");
asm("push $128 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper129");
asm(".align   4");
asm("");
asm("isr_wrapper129:");
asm("push $0 // push dummy error code");
asm("push $129 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper130");
asm(".align   4");
asm("");
asm("isr_wrapper130:");
asm("push $0 // push dummy error code");
asm("push $130 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper131");
asm(".align   4");
asm("");
asm("isr_wrapper131:");
asm("push $0 // push dummy error code");
asm("push $131 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper132");
asm(".align   4");
asm("");
asm("isr_wrapper132:");
asm("push $0 // push dummy error code");
asm("push $132 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper133");
asm(".align   4");
asm("");
asm("isr_wrapper133:");
asm("push $0 // push dummy error code");
asm("push $133 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper134");
asm(".align   4");
asm("");
asm("isr_wrapper134:");
asm("push $0 // push dummy error code");
asm("push $134 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper135");
asm(".align   4");
asm("");
asm("isr_wrapper135:");
asm("push $0 // push dummy error code");
asm("push $135 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper136");
asm(".align   4");
asm("");
asm("isr_wrapper136:");
asm("push $0 // push dummy error code");
asm("push $136 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper137");
asm(".align   4");
asm("");
asm("isr_wrapper137:");
asm("push $0 // push dummy error code");
asm("push $137 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper138");
asm(".align   4");
asm("");
asm("isr_wrapper138:");
asm("push $0 // push dummy error code");
asm("push $138 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper139");
asm(".align   4");
asm("");
asm("isr_wrapper139:");
asm("push $0 // push dummy error code");
asm("push $139 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper140");
asm(".align   4");
asm("");
asm("isr_wrapper140:");
asm("push $0 // push dummy error code");
asm("push $140 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper141");
asm(".align   4");
asm("");
asm("isr_wrapper141:");
asm("push $0 // push dummy error code");
asm("push $141 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper142");
asm(".align   4");
asm("");
asm("isr_wrapper142:");
asm("push $0 // push dummy error code");
asm("push $142 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper143");
asm(".align   4");
asm("");
asm("isr_wrapper143:");
asm("push $0 // push dummy error code");
asm("push $143 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper144");
asm(".align   4");
asm("");
asm("isr_wrapper144:");
asm("push $0 // push dummy error code");
asm("push $144 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper145");
asm(".align   4");
asm("");
asm("isr_wrapper145:");
asm("push $0 // push dummy error code");
asm("push $145 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper146");
asm(".align   4");
asm("");
asm("isr_wrapper146:");
asm("push $0 // push dummy error code");
asm("push $146 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper147");
asm(".align   4");
asm("");
asm("isr_wrapper147:");
asm("push $0 // push dummy error code");
asm("push $147 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper148");
asm(".align   4");
asm("");
asm("isr_wrapper148:");
asm("push $0 // push dummy error code");
asm("push $148 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper149");
asm(".align   4");
asm("");
asm("isr_wrapper149:");
asm("push $0 // push dummy error code");
asm("push $149 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper150");
asm(".align   4");
asm("");
asm("isr_wrapper150:");
asm("push $0 // push dummy error code");
asm("push $150 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper151");
asm(".align   4");
asm("");
asm("isr_wrapper151:");
asm("push $0 // push dummy error code");
asm("push $151 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper152");
asm(".align   4");
asm("");
asm("isr_wrapper152:");
asm("push $0 // push dummy error code");
asm("push $152 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper153");
asm(".align   4");
asm("");
asm("isr_wrapper153:");
asm("push $0 // push dummy error code");
asm("push $153 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper154");
asm(".align   4");
asm("");
asm("isr_wrapper154:");
asm("push $0 // push dummy error code");
asm("push $154 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper155");
asm(".align   4");
asm("");
asm("isr_wrapper155:");
asm("push $0 // push dummy error code");
asm("push $155 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper156");
asm(".align   4");
asm("");
asm("isr_wrapper156:");
asm("push $0 // push dummy error code");
asm("push $156 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper157");
asm(".align   4");
asm("");
asm("isr_wrapper157:");
asm("push $0 // push dummy error code");
asm("push $157 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper158");
asm(".align   4");
asm("");
asm("isr_wrapper158:");
asm("push $0 // push dummy error code");
asm("push $158 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper159");
asm(".align   4");
asm("");
asm("isr_wrapper159:");
asm("push $0 // push dummy error code");
asm("push $159 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper160");
asm(".align   4");
asm("");
asm("isr_wrapper160:");
asm("push $0 // push dummy error code");
asm("push $160 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper161");
asm(".align   4");
asm("");
asm("isr_wrapper161:");
asm("push $0 // push dummy error code");
asm("push $161 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper162");
asm(".align   4");
asm("");
asm("isr_wrapper162:");
asm("push $0 // push dummy error code");
asm("push $162 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper163");
asm(".align   4");
asm("");
asm("isr_wrapper163:");
asm("push $0 // push dummy error code");
asm("push $163 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper164");
asm(".align   4");
asm("");
asm("isr_wrapper164:");
asm("push $0 // push dummy error code");
asm("push $164 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper165");
asm(".align   4");
asm("");
asm("isr_wrapper165:");
asm("push $0 // push dummy error code");
asm("push $165 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper166");
asm(".align   4");
asm("");
asm("isr_wrapper166:");
asm("push $0 // push dummy error code");
asm("push $166 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper167");
asm(".align   4");
asm("");
asm("isr_wrapper167:");
asm("push $0 // push dummy error code");
asm("push $167 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper168");
asm(".align   4");
asm("");
asm("isr_wrapper168:");
asm("push $0 // push dummy error code");
asm("push $168 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper169");
asm(".align   4");
asm("");
asm("isr_wrapper169:");
asm("push $0 // push dummy error code");
asm("push $169 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper170");
asm(".align   4");
asm("");
asm("isr_wrapper170:");
asm("push $0 // push dummy error code");
asm("push $170 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper171");
asm(".align   4");
asm("");
asm("isr_wrapper171:");
asm("push $0 // push dummy error code");
asm("push $171 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper172");
asm(".align   4");
asm("");
asm("isr_wrapper172:");
asm("push $0 // push dummy error code");
asm("push $172 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper173");
asm(".align   4");
asm("");
asm("isr_wrapper173:");
asm("push $0 // push dummy error code");
asm("push $173 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper174");
asm(".align   4");
asm("");
asm("isr_wrapper174:");
asm("push $0 // push dummy error code");
asm("push $174 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper175");
asm(".align   4");
asm("");
asm("isr_wrapper175:");
asm("push $0 // push dummy error code");
asm("push $175 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper176");
asm(".align   4");
asm("");
asm("isr_wrapper176:");
asm("push $0 // push dummy error code");
asm("push $176 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper177");
asm(".align   4");
asm("");
asm("isr_wrapper177:");
asm("push $0 // push dummy error code");
asm("push $177 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper178");
asm(".align   4");
asm("");
asm("isr_wrapper178:");
asm("push $0 // push dummy error code");
asm("push $178 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper179");
asm(".align   4");
asm("");
asm("isr_wrapper179:");
asm("push $0 // push dummy error code");
asm("push $179 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper180");
asm(".align   4");
asm("");
asm("isr_wrapper180:");
asm("push $0 // push dummy error code");
asm("push $180 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper181");
asm(".align   4");
asm("");
asm("isr_wrapper181:");
asm("push $0 // push dummy error code");
asm("push $181 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper182");
asm(".align   4");
asm("");
asm("isr_wrapper182:");
asm("push $0 // push dummy error code");
asm("push $182 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper183");
asm(".align   4");
asm("");
asm("isr_wrapper183:");
asm("push $0 // push dummy error code");
asm("push $183 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper184");
asm(".align   4");
asm("");
asm("isr_wrapper184:");
asm("push $0 // push dummy error code");
asm("push $184 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper185");
asm(".align   4");
asm("");
asm("isr_wrapper185:");
asm("push $0 // push dummy error code");
asm("push $185 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper186");
asm(".align   4");
asm("");
asm("isr_wrapper186:");
asm("push $0 // push dummy error code");
asm("push $186 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper187");
asm(".align   4");
asm("");
asm("isr_wrapper187:");
asm("push $0 // push dummy error code");
asm("push $187 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper188");
asm(".align   4");
asm("");
asm("isr_wrapper188:");
asm("push $0 // push dummy error code");
asm("push $188 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper189");
asm(".align   4");
asm("");
asm("isr_wrapper189:");
asm("push $0 // push dummy error code");
asm("push $189 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper190");
asm(".align   4");
asm("");
asm("isr_wrapper190:");
asm("push $0 // push dummy error code");
asm("push $190 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper191");
asm(".align   4");
asm("");
asm("isr_wrapper191:");
asm("push $0 // push dummy error code");
asm("push $191 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper192");
asm(".align   4");
asm("");
asm("isr_wrapper192:");
asm("push $0 // push dummy error code");
asm("push $192 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper193");
asm(".align   4");
asm("");
asm("isr_wrapper193:");
asm("push $0 // push dummy error code");
asm("push $193 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper194");
asm(".align   4");
asm("");
asm("isr_wrapper194:");
asm("push $0 // push dummy error code");
asm("push $194 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper195");
asm(".align   4");
asm("");
asm("isr_wrapper195:");
asm("push $0 // push dummy error code");
asm("push $195 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper196");
asm(".align   4");
asm("");
asm("isr_wrapper196:");
asm("push $0 // push dummy error code");
asm("push $196 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper197");
asm(".align   4");
asm("");
asm("isr_wrapper197:");
asm("push $0 // push dummy error code");
asm("push $197 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper198");
asm(".align   4");
asm("");
asm("isr_wrapper198:");
asm("push $0 // push dummy error code");
asm("push $198 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper199");
asm(".align   4");
asm("");
asm("isr_wrapper199:");
asm("push $0 // push dummy error code");
asm("push $199 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper200");
asm(".align   4");
asm("");
asm("isr_wrapper200:");
asm("push $0 // push dummy error code");
asm("push $200 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper201");
asm(".align   4");
asm("");
asm("isr_wrapper201:");
asm("push $0 // push dummy error code");
asm("push $201 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper202");
asm(".align   4");
asm("");
asm("isr_wrapper202:");
asm("push $0 // push dummy error code");
asm("push $202 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper203");
asm(".align   4");
asm("");
asm("isr_wrapper203:");
asm("push $0 // push dummy error code");
asm("push $203 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper204");
asm(".align   4");
asm("");
asm("isr_wrapper204:");
asm("push $0 // push dummy error code");
asm("push $204 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper205");
asm(".align   4");
asm("");
asm("isr_wrapper205:");
asm("push $0 // push dummy error code");
asm("push $205 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper206");
asm(".align   4");
asm("");
asm("isr_wrapper206:");
asm("push $0 // push dummy error code");
asm("push $206 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper207");
asm(".align   4");
asm("");
asm("isr_wrapper207:");
asm("push $0 // push dummy error code");
asm("push $207 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper208");
asm(".align   4");
asm("");
asm("isr_wrapper208:");
asm("push $0 // push dummy error code");
asm("push $208 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper209");
asm(".align   4");
asm("");
asm("isr_wrapper209:");
asm("push $0 // push dummy error code");
asm("push $209 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper210");
asm(".align   4");
asm("");
asm("isr_wrapper210:");
asm("push $0 // push dummy error code");
asm("push $210 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper211");
asm(".align   4");
asm("");
asm("isr_wrapper211:");
asm("push $0 // push dummy error code");
asm("push $211 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper212");
asm(".align   4");
asm("");
asm("isr_wrapper212:");
asm("push $0 // push dummy error code");
asm("push $212 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper213");
asm(".align   4");
asm("");
asm("isr_wrapper213:");
asm("push $0 // push dummy error code");
asm("push $213 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper214");
asm(".align   4");
asm("");
asm("isr_wrapper214:");
asm("push $0 // push dummy error code");
asm("push $214 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper215");
asm(".align   4");
asm("");
asm("isr_wrapper215:");
asm("push $0 // push dummy error code");
asm("push $215 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper216");
asm(".align   4");
asm("");
asm("isr_wrapper216:");
asm("push $0 // push dummy error code");
asm("push $216 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper217");
asm(".align   4");
asm("");
asm("isr_wrapper217:");
asm("push $0 // push dummy error code");
asm("push $217 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper218");
asm(".align   4");
asm("");
asm("isr_wrapper218:");
asm("push $0 // push dummy error code");
asm("push $218 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper219");
asm(".align   4");
asm("");
asm("isr_wrapper219:");
asm("push $0 // push dummy error code");
asm("push $219 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper220");
asm(".align   4");
asm("");
asm("isr_wrapper220:");
asm("push $0 // push dummy error code");
asm("push $220 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper221");
asm(".align   4");
asm("");
asm("isr_wrapper221:");
asm("push $0 // push dummy error code");
asm("push $221 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper222");
asm(".align   4");
asm("");
asm("isr_wrapper222:");
asm("push $0 // push dummy error code");
asm("push $222 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper223");
asm(".align   4");
asm("");
asm("isr_wrapper223:");
asm("push $0 // push dummy error code");
asm("push $223 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper224");
asm(".align   4");
asm("");
asm("isr_wrapper224:");
asm("push $0 // push dummy error code");
asm("push $224 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper225");
asm(".align   4");
asm("");
asm("isr_wrapper225:");
asm("push $0 // push dummy error code");
asm("push $225 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper226");
asm(".align   4");
asm("");
asm("isr_wrapper226:");
asm("push $0 // push dummy error code");
asm("push $226 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper227");
asm(".align   4");
asm("");
asm("isr_wrapper227:");
asm("push $0 // push dummy error code");
asm("push $227 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper228");
asm(".align   4");
asm("");
asm("isr_wrapper228:");
asm("push $0 // push dummy error code");
asm("push $228 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper229");
asm(".align   4");
asm("");
asm("isr_wrapper229:");
asm("push $0 // push dummy error code");
asm("push $229 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper230");
asm(".align   4");
asm("");
asm("isr_wrapper230:");
asm("push $0 // push dummy error code");
asm("push $230 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper231");
asm(".align   4");
asm("");
asm("isr_wrapper231:");
asm("push $0 // push dummy error code");
asm("push $231 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper232");
asm(".align   4");
asm("");
asm("isr_wrapper232:");
asm("push $0 // push dummy error code");
asm("push $232 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper233");
asm(".align   4");
asm("");
asm("isr_wrapper233:");
asm("push $0 // push dummy error code");
asm("push $233 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper234");
asm(".align   4");
asm("");
asm("isr_wrapper234:");
asm("push $0 // push dummy error code");
asm("push $234 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper235");
asm(".align   4");
asm("");
asm("isr_wrapper235:");
asm("push $0 // push dummy error code");
asm("push $235 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper236");
asm(".align   4");
asm("");
asm("isr_wrapper236:");
asm("push $0 // push dummy error code");
asm("push $236 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper237");
asm(".align   4");
asm("");
asm("isr_wrapper237:");
asm("push $0 // push dummy error code");
asm("push $237 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper238");
asm(".align   4");
asm("");
asm("isr_wrapper238:");
asm("push $0 // push dummy error code");
asm("push $238 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper239");
asm(".align   4");
asm("");
asm("isr_wrapper239:");
asm("push $0 // push dummy error code");
asm("push $239 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper240");
asm(".align   4");
asm("");
asm("isr_wrapper240:");
asm("push $0 // push dummy error code");
asm("push $240 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper241");
asm(".align   4");
asm("");
asm("isr_wrapper241:");
asm("push $0 // push dummy error code");
asm("push $241 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper242");
asm(".align   4");
asm("");
asm("isr_wrapper242:");
asm("push $0 // push dummy error code");
asm("push $242 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper243");
asm(".align   4");
asm("");
asm("isr_wrapper243:");
asm("push $0 // push dummy error code");
asm("push $243 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper244");
asm(".align   4");
asm("");
asm("isr_wrapper244:");
asm("push $0 // push dummy error code");
asm("push $244 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper245");
asm(".align   4");
asm("");
asm("isr_wrapper245:");
asm("push $0 // push dummy error code");
asm("push $245 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper246");
asm(".align   4");
asm("");
asm("isr_wrapper246:");
asm("push $0 // push dummy error code");
asm("push $246 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper247");
asm(".align   4");
asm("");
asm("isr_wrapper247:");
asm("push $0 // push dummy error code");
asm("push $247 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper248");
asm(".align   4");
asm("");
asm("isr_wrapper248:");
asm("push $0 // push dummy error code");
asm("push $248 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper249");
asm(".align   4");
asm("");
asm("isr_wrapper249:");
asm("push $0 // push dummy error code");
asm("push $249 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper250");
asm(".align   4");
asm("");
asm("isr_wrapper250:");
asm("push $0 // push dummy error code");
asm("push $250 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper251");
asm(".align   4");
asm("");
asm("isr_wrapper251:");
asm("push $0 // push dummy error code");
asm("push $251 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper252");
asm(".align   4");
asm("");
asm("isr_wrapper252:");
asm("push $0 // push dummy error code");
asm("push $252 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper253");
asm(".align   4");
asm("");
asm("isr_wrapper253:");
asm("push $0 // push dummy error code");
asm("push $253 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper254");
asm(".align   4");
asm("");
asm("isr_wrapper254:");
asm("push $0 // push dummy error code");
asm("push $254 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".local   isr_wrapper255");
asm(".align   4");
asm("");
asm("isr_wrapper255:");
asm("push $0 // push dummy error code");
asm("push $255 //");
asm("call isr_asm //");
asm("add $0x10, %rsp // pop the interrupt number and the error code.");
asm("iretq //");
asm("");
asm("");
asm(".data");
asm(".global isrs_list");
asm("isrs_list:");
asm(".quad isr_wrapper0");
asm(".quad isr_wrapper1");
asm(".quad isr_wrapper2");
asm(".quad isr_wrapper3");
asm(".quad isr_wrapper4");
asm(".quad isr_wrapper5");
asm(".quad isr_wrapper6");
asm(".quad isr_wrapper7");
asm(".quad isr_wrapper8");
asm(".quad isr_wrapper9");
asm(".quad isr_wrapper10");
asm(".quad isr_wrapper11");
asm(".quad isr_wrapper12");
asm(".quad isr_wrapper13");
asm(".quad isr_wrapper14");
asm(".quad isr_wrapper15");
asm(".quad isr_wrapper16");
asm(".quad isr_wrapper17");
asm(".quad isr_wrapper18");
asm(".quad isr_wrapper19");
asm(".quad isr_wrapper20");
asm(".quad isr_wrapper21");
asm(".quad isr_wrapper22");
asm(".quad isr_wrapper23");
asm(".quad isr_wrapper24");
asm(".quad isr_wrapper25");
asm(".quad isr_wrapper26");
asm(".quad isr_wrapper27");
asm(".quad isr_wrapper28");
asm(".quad isr_wrapper29");
asm(".quad isr_wrapper30");
asm(".quad isr_wrapper31");
asm(".quad isr_wrapper32");
asm(".quad isr_wrapper33");
asm(".quad isr_wrapper34");
asm(".quad isr_wrapper35");
asm(".quad isr_wrapper36");
asm(".quad isr_wrapper37");
asm(".quad isr_wrapper38");
asm(".quad isr_wrapper39");
asm(".quad isr_wrapper40");
asm(".quad isr_wrapper41");
asm(".quad isr_wrapper42");
asm(".quad isr_wrapper43");
asm(".quad isr_wrapper44");
asm(".quad isr_wrapper45");
asm(".quad isr_wrapper46");
asm(".quad isr_wrapper47");
asm(".quad isr_wrapper48");
asm(".quad isr_wrapper49");
asm(".quad isr_wrapper50");
asm(".quad isr_wrapper51");
asm(".quad isr_wrapper52");
asm(".quad isr_wrapper53");
asm(".quad isr_wrapper54");
asm(".quad isr_wrapper55");
asm(".quad isr_wrapper56");
asm(".quad isr_wrapper57");
asm(".quad isr_wrapper58");
asm(".quad isr_wrapper59");
asm(".quad isr_wrapper60");
asm(".quad isr_wrapper61");
asm(".quad isr_wrapper62");
asm(".quad isr_wrapper63");
asm(".quad isr_wrapper64");
asm(".quad isr_wrapper65");
asm(".quad isr_wrapper66");
asm(".quad isr_wrapper67");
asm(".quad isr_wrapper68");
asm(".quad isr_wrapper69");
asm(".quad isr_wrapper70");
asm(".quad isr_wrapper71");
asm(".quad isr_wrapper72");
asm(".quad isr_wrapper73");
asm(".quad isr_wrapper74");
asm(".quad isr_wrapper75");
asm(".quad isr_wrapper76");
asm(".quad isr_wrapper77");
asm(".quad isr_wrapper78");
asm(".quad isr_wrapper79");
asm(".quad isr_wrapper80");
asm(".quad isr_wrapper81");
asm(".quad isr_wrapper82");
asm(".quad isr_wrapper83");
asm(".quad isr_wrapper84");
asm(".quad isr_wrapper85");
asm(".quad isr_wrapper86");
asm(".quad isr_wrapper87");
asm(".quad isr_wrapper88");
asm(".quad isr_wrapper89");
asm(".quad isr_wrapper90");
asm(".quad isr_wrapper91");
asm(".quad isr_wrapper92");
asm(".quad isr_wrapper93");
asm(".quad isr_wrapper94");
asm(".quad isr_wrapper95");
asm(".quad isr_wrapper96");
asm(".quad isr_wrapper97");
asm(".quad isr_wrapper98");
asm(".quad isr_wrapper99");
asm(".quad isr_wrapper100");
asm(".quad isr_wrapper101");
asm(".quad isr_wrapper102");
asm(".quad isr_wrapper103");
asm(".quad isr_wrapper104");
asm(".quad isr_wrapper105");
asm(".quad isr_wrapper106");
asm(".quad isr_wrapper107");
asm(".quad isr_wrapper108");
asm(".quad isr_wrapper109");
asm(".quad isr_wrapper110");
asm(".quad isr_wrapper111");
asm(".quad isr_wrapper112");
asm(".quad isr_wrapper113");
asm(".quad isr_wrapper114");
asm(".quad isr_wrapper115");
asm(".quad isr_wrapper116");
asm(".quad isr_wrapper117");
asm(".quad isr_wrapper118");
asm(".quad isr_wrapper119");
asm(".quad isr_wrapper120");
asm(".quad isr_wrapper121");
asm(".quad isr_wrapper122");
asm(".quad isr_wrapper123");
asm(".quad isr_wrapper124");
asm(".quad isr_wrapper125");
asm(".quad isr_wrapper126");
asm(".quad isr_wrapper127");
asm(".quad isr_wrapper128");
asm(".quad isr_wrapper129");
asm(".quad isr_wrapper130");
asm(".quad isr_wrapper131");
asm(".quad isr_wrapper132");
asm(".quad isr_wrapper133");
asm(".quad isr_wrapper134");
asm(".quad isr_wrapper135");
asm(".quad isr_wrapper136");
asm(".quad isr_wrapper137");
asm(".quad isr_wrapper138");
asm(".quad isr_wrapper139");
asm(".quad isr_wrapper140");
asm(".quad isr_wrapper141");
asm(".quad isr_wrapper142");
asm(".quad isr_wrapper143");
asm(".quad isr_wrapper144");
asm(".quad isr_wrapper145");
asm(".quad isr_wrapper146");
asm(".quad isr_wrapper147");
asm(".quad isr_wrapper148");
asm(".quad isr_wrapper149");
asm(".quad isr_wrapper150");
asm(".quad isr_wrapper151");
asm(".quad isr_wrapper152");
asm(".quad isr_wrapper153");
asm(".quad isr_wrapper154");
asm(".quad isr_wrapper155");
asm(".quad isr_wrapper156");
asm(".quad isr_wrapper157");
asm(".quad isr_wrapper158");
asm(".quad isr_wrapper159");
asm(".quad isr_wrapper160");
asm(".quad isr_wrapper161");
asm(".quad isr_wrapper162");
asm(".quad isr_wrapper163");
asm(".quad isr_wrapper164");
asm(".quad isr_wrapper165");
asm(".quad isr_wrapper166");
asm(".quad isr_wrapper167");
asm(".quad isr_wrapper168");
asm(".quad isr_wrapper169");
asm(".quad isr_wrapper170");
asm(".quad isr_wrapper171");
asm(".quad isr_wrapper172");
asm(".quad isr_wrapper173");
asm(".quad isr_wrapper174");
asm(".quad isr_wrapper175");
asm(".quad isr_wrapper176");
asm(".quad isr_wrapper177");
asm(".quad isr_wrapper178");
asm(".quad isr_wrapper179");
asm(".quad isr_wrapper180");
asm(".quad isr_wrapper181");
asm(".quad isr_wrapper182");
asm(".quad isr_wrapper183");
asm(".quad isr_wrapper184");
asm(".quad isr_wrapper185");
asm(".quad isr_wrapper186");
asm(".quad isr_wrapper187");
asm(".quad isr_wrapper188");
asm(".quad isr_wrapper189");
asm(".quad isr_wrapper190");
asm(".quad isr_wrapper191");
asm(".quad isr_wrapper192");
asm(".quad isr_wrapper193");
asm(".quad isr_wrapper194");
asm(".quad isr_wrapper195");
asm(".quad isr_wrapper196");
asm(".quad isr_wrapper197");
asm(".quad isr_wrapper198");
asm(".quad isr_wrapper199");
asm(".quad isr_wrapper200");
asm(".quad isr_wrapper201");
asm(".quad isr_wrapper202");
asm(".quad isr_wrapper203");
asm(".quad isr_wrapper204");
asm(".quad isr_wrapper205");
asm(".quad isr_wrapper206");
asm(".quad isr_wrapper207");
asm(".quad isr_wrapper208");
asm(".quad isr_wrapper209");
asm(".quad isr_wrapper210");
asm(".quad isr_wrapper211");
asm(".quad isr_wrapper212");
asm(".quad isr_wrapper213");
asm(".quad isr_wrapper214");
asm(".quad isr_wrapper215");
asm(".quad isr_wrapper216");
asm(".quad isr_wrapper217");
asm(".quad isr_wrapper218");
asm(".quad isr_wrapper219");
asm(".quad isr_wrapper220");
asm(".quad isr_wrapper221");
asm(".quad isr_wrapper222");
asm(".quad isr_wrapper223");
asm(".quad isr_wrapper224");
asm(".quad isr_wrapper225");
asm(".quad isr_wrapper226");
asm(".quad isr_wrapper227");
asm(".quad isr_wrapper228");
asm(".quad isr_wrapper229");
asm(".quad isr_wrapper230");
asm(".quad isr_wrapper231");
asm(".quad isr_wrapper232");
asm(".quad isr_wrapper233");
asm(".quad isr_wrapper234");
asm(".quad isr_wrapper235");
asm(".quad isr_wrapper236");
asm(".quad isr_wrapper237");
asm(".quad isr_wrapper238");
asm(".quad isr_wrapper239");
asm(".quad isr_wrapper240");
asm(".quad isr_wrapper241");
asm(".quad isr_wrapper242");
asm(".quad isr_wrapper243");
asm(".quad isr_wrapper244");
asm(".quad isr_wrapper245");
asm(".quad isr_wrapper246");
asm(".quad isr_wrapper247");
asm(".quad isr_wrapper248");
asm(".quad isr_wrapper249");
asm(".quad isr_wrapper250");
asm(".quad isr_wrapper251");
asm(".quad isr_wrapper252");
asm(".quad isr_wrapper253");
asm(".quad isr_wrapper254");
asm(".quad isr_wrapper255");
asm("");